name: Deploy Church API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Clojure tools
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.3.1087.sh
        chmod +x linux-install-1.10.3.1087.sh
        sudo ./linux-install-1.10.3.1087.sh

    - name: Build application
      run: clojure -T:build uber

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/church-api.git
        git push heroku main
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
